### ISSUE TITLE
Grid Path To Window Path helper function

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#100]
manually converting between paths for the navigation grid and the window's coordinate system is tedious and error prone.

We should add one or more functions facilitate easy conversion between the two. 

This could either be added to NavigationTools or to CoordinateConverter

**Comment by gyurgyma** [comment]
I think it ought to go onto CoordinateConverter. Where do we manually do it now? I'd like to copy paste some code.

**Comment by gyurgyma** [comment]
Issue 91 needs to close first.

**Comment by gyurgyma** [comment]
Merged into Dev.
