### ISSUE TITLE
Test all CTRs

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#101]
All constructors should have test coverage.

**Comment by malexmc** [comment]
Posting these findings here for reference. The only classes OppenCppCoverage decided had holes in constructor testing were the following:

CoreEventController
    -Test which creates a blank CEC and deletes it immediately to check CEC for memory leaks.

CoordinateConverter
    -Test the default constructor.

Cluster and ClusterGreenhouse
    -All constructors (and everything else within them) need testing.

**Comment by malexmc** [comment]
i101-TestAllCTRs:
    -Added a test which creates and deletes a non-overridden CoreEventController for memory leak checking.
    -Added a test which creates a default CoordinateConverter.
    -Added ClusterTests and ClusterGreenhousTests files with constructor tests.

**Comment by gyurgyma** [comment]
@malexmc 
1. Comments should always have a space after the slashes (ei: // Text here.) 
2. Misspelled "dimensions" as "demensions" in greenhouse test land.
3. "ctr/Ctr" should be standardized everywhere. I dont care if its minuscule or include majusclule 'c' just dont change only one. I think you should change every instance of "ctr" to "Ctr" and "dtr" to "Dtr". Other than that. I think the tests look good and so long as CPP whatever isnt yelling then we gucci. After those fixes ill rereview

**Comment by lavinrp** [comment]
@gyurgyma 
1. fixed wherever I found it
2. fixed
3. changed all Ctr to CTR to fit with our style guide having acronyms and abbreviations in all caps.
  * Note: this was only changed for unit test names

**Comment by lavinrp** [comment]
It looks to me that we have the coverage that the issue requested.

**Comment by gyurgyma** [comment]
Merged into Dev
