### ISSUE TITLE
Alphabetize BackboneBaseExceptions classes

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#102]
Alphabetizing the exceptions in BackboneBaseExceptions will make things more readable for some people. Worth doing.

**Comment by lavinrp** [comment]
@gyurgyma is this pushed? Cant see it.

**Comment by gyurgyma** [comment]
@lavinrp try now i repushed.

**Comment by lavinrp** [comment]
@gyurgyma Thanks. Its there now.
