### ISSUE TITLE
Make CompoundSprite behave like SF::Transormable

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#103]
Compound sprite is little more than two vectors right now. Give it its own center position.

Add rotate function.

Add setScale functions.

**Comment by lavinrp** [comment]
Compound sprite is little more than two vectors right now. Give it its own center position. Set the compound sprite's center position as the origin for all of its sub-sprites.

Add rotate function.

Possibly add animated sprites to the sprites vector?

**Comment by gyurgyma** [comment]
Merged into Dev
