### ISSUE TITLE
Cluster Greenhouse map generation tweeks

### ISSUE THREAD

**Issue by bauerbp** [lavinrp/GameBackbone#105]
There are some bugs in the map generation.

**Comment by gyurgyma** [comment]
@bauerbp can you ist out some of the bugs so we know what to review against?

**Comment by bauerbp** [comment]
A known bug includes clusters crawling up the edge of the graph (fix is pushed to i105).  Other bugs are waiting to be found.

**Comment by lavinrp** [comment]
@bauerbp 
Does chooseClusterToAddTo need to be public?
can we give that a better name? getClusterToGrow? chooseClusterToGrow?

Can we add these changes as part of this issue?

**Comment by lavinrp** [comment]
@bauerbp 
Cluster and ClusterGreenhouse should follow the rule of 5.
As part of this issue can you add the necessary constructors / assignment operators to satisfy this please?

**Comment by lavinrp** [comment]
Were not going to touch this since were refactoring the system
