### ISSUE TITLE
Look into shallow wrapper for sf::Sprite

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#107]
sf::Sprite has a non virtual destructor. 

Currently AnimatedSprite is the only thing that inherits from sprite, but there are times where we store animated sprites in containers of sprites.

If we rely on these containers to as our way of tracking our memory and deleting the animated sprites we will have a memory leak.

In my mind the risk of someone (or us) storing an animated sprite as a sprite and causing a leak is too great to leave as a possibility.

If we create a GB::Sprite class that has a virtual destructor this problem largely goes away. (people could still cause a leak by storing things as sf::sprites, but we would strongly encourage the use of GB::Sprites)

The GB::Sprite would be a shallow wrapper around sf::Sprite, with the only change being a virtual destructor.

The sf::Sprite destructor is default so we could even do virtual GB::~Sprite() = default

**Comment by gyurgyma** [comment]
@lavinrp So, change every instance of sf::Sprite to GB::Sprite? That'll be a rough change. neato.

**Comment by lavinrp** [comment]
After much thought and an initial implementation, I have decided that this is more trouble than it is worth. Clients will just have to be smart enough to not try to destroy animated sprites through a non-existent virtual destructor on sf::Sprite
