### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by Peaslek** [lavinrp/GameBackbone#110]
If we want anyone to be able to contribute, create a README describing how to

- Build/test
- Contribute
- Coding guidelines
- etc

**Comment by lavinrp** [comment]
@Peaslek 
Dont have anything on how to Contribute / coding guidelines in yet. The guidelines will prob be a different md file. What do you think so far?

@gyurgyma I have found myself woefully unable to adequately describe our versioning. Thoughts?

**Comment by gyurgyma** [comment]
@lavinrp 
1. the coding styleguide might fit for the first part you said.
2. Not wholly sure what you mean. What's confusing about the versioning? It's just standard software versioning.

**Comment by lavinrp** [comment]
@gyurgyma Take a look at the versioning tab and compare it to http://semver.org/
We don't exactly follow what they are doing at the moment.

If you can think of a better way to word what I have there, please change it.
