### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#113]
Add explicit license to the project.

**Comment by lavinrp** [comment]
Would like 100% approval before merging into dev.

If I missed someone, or if you don't want your name on the license, then edit yourself in/out.

Post approval/disapproval below

**Comment by gyurgyma** [comment]
I'd like the name AgreeableDeerGames somewhere in there. perhaps before the list of individual's names. what's everyone think?

**Comment by lavinrp** [comment]
Added AGD to the license
