### ISSUE TITLE
Improve interaction with GameRegion children and neighbors

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#123]
Game regions currently have some strange behavior with neighbor and child regions.
The child and neighbor vectors of regions are mutably returned by getters and this is the only way to reach individual children or neighbors.

Now that neighbors and children are vectors, it make make more sense to change the getters to return a reference to a child or neighbor, instead of the entire vector of them.

nullptr neighbors and children also behave strange when being removed. Currently neighbors and children can only be accessed by searching for their address. If there are multiple nullptr addresses in one container then the first one is removed. This is a strange and undesired scenario, but it is possible and the behavior of game region should be better defined to handle this.

**Comment by gyurgyma** [comment]
Converting them to:
GameRegion* GameRegion::getNeighborRegion(int index) {
    return neighborRegions.at(index);
}

GameRegion* GameRegion::getChildRegion(int index) {
    return childRegions.at(index);
}

Doing this though means that we probably need a getNumberOfX and maybe even an isXOfRegion.

Should talk about

**Comment by gyurgyma** [comment]
Maybe a Vector const * const

**Comment by lavinrp** [comment]
3 options:
enum,
tags,
Graph of all Game regions within the CEC

**Comment by lavinrp** [comment]
Attempting a tag implementation

**Comment by lavinrp** [comment]
Attempting to use variadic templates with std::variant to allow users to input any number of desired enums.

running into clang++ bug with variant though.
https://stackoverflow.com/questions/46859053/stdvisit-for-variant-fails-to-compile-under-clang-5?rq=1

Will finish task with g++ then assess the clang situation.

**Comment by lavinrp** [comment]
Chose to just make existing associations const

**Comment by gyurgyma** [comment]
const std::list<Updatable*>* getUpdatables();
        const std::list<sf::Sprite*>* getDrawables();

these lists should both be changed to vector or deque.

**Comment by gyurgyma** [comment]
Fixed and merged into dev
