### ISSUE TITLE
Linux Cmake Support

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#130]
Make Cmake build with linux,

FindGameBackbone

**Comment by lavinrp** [comment]
While were here we should try to see if we can make the unit test window stay open on windows.

**Comment by gyurgyma** [comment]
Getting Started: 
Windows and Linux are in different orders. PLZ.

Environment:
Environment Variables don't have to be system wide.

Misc Setup:
Subheaders should be bolded rather than capped.

Numbers. ei: 1.0 1.1 etc.

Contributors vs Users.

Submitting Issues:
Always applicable to give steps.

**Comment by lavinrp** [comment]
Readme changes are now tracked by #135 

1. Clean recompile now works.
2. Boost tests now build for boost 1.67
3. Environment vars are once again used if there is no value in GB_BuildVars.txt

This has only been tested on Ubuntu 18.04

**Comment by lavinrp** [comment]
@flounderK @gyurgyma @Christopher-Ochs 
This needs tested across all Operating systems due to its meddling with environment variables

**Comment by gyurgyma** [comment]
Windows updated to SFML: 2.5.0, TGUI: 0.7.7, using Boost: 1.67 14.1
Works and all tests are passing

**Comment by gyurgyma** [comment]
Merged into Dev and Master
