### ISSUE TITLE
Unitialized values 

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#132]
GB is riddled with values that have never been initialized. This is partly because we got sloppy, and partly because we couldn't catch the errors at runtime b/c our compiler would somehow init them for us.

Now with CMake the compiler has stopped doing our job.

Lets use valgrind to find our uninitialized values and initialize them all
Run Unit tests and the demo through valgrind and fix any memory errors that it finds.

**Comment by lavinrp** [comment]
AnimatedSprite.isReverse is never initialized.

**Comment by gyurgyma** [comment]
Since this is unix/linux, i cannot participate. i can fix subsequent issues as needed though

**Comment by flounderK** [comment]
The FileReader and FileManager tests are currently failing because the when BadFile is thrown the tests continue on. FIleReaderTests.cpp should probably be refactored so that these tests are skipped when BadFile is thrown.

**Comment by lavinrp** [comment]
@flounderK 
In an ideal world BadFile should not be thrown.
The tests failing when bad file is thrown is usually a good thing.

In this instance its causing a false alarm, but thats because our testing setup isn't finding the files correctly.

After our testing setup is back working consistently the tests failing will be a good thing.

We may want to add a catch to each of the tests if this continues to be a problem,
but that catch shouldn't skip the tests it should cause them to report a failure.


When tests fail normally it doesn't halt the rest of the test execution.

**Comment by lavinrp** [comment]
@flounderK 
The BadFile exception is fixed in #134

**Comment by lavinrp** [comment]
we seem to have got these.

**Comment by lavinrp** [comment]
AnimatedSprite.isReverse is never initialized still. Reopening.

**Comment by flounderK** [comment]
Initialized isReverse
