### ISSUE TITLE
Add framesSpentInAnimation to AnimatedSprite

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#133]
RE and possibly other games will utilize the amount of frames spent in a given animation on an AnimatedSprite. This should be reset to 0 when setting an animation, and it should have its own reset function.

**Comment by gyurgyma** [comment]
framesSpentInCurrentAnimation has been added and tests updated. Needs Review.

**Comment by lavinrp** [comment]
Logic is sound. Tests are sound.
Good to merge.
