### ISSUE TITLE
Update README for better readability

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#135]
From #130 

@gyurgyma: 
> Getting Started:
> Windows and Linux are in different orders. PLZ.
> 
> Environment:
> Environment Variables don't have to be system wide.
> 
> Misc Setup:
> Subheaders should be bolded rather than capped.
> 
> Numbers. ei: 1.0 1.1 etc.
> 
> Contributors vs Users.
> 
> Submitting Issues:
> Always applicable to give steps.

**Comment by gyurgyma** [comment]
I'm now frustrated after having to figure out the version of dependencies 3 times. For ease of use, lets add at least stable examples that we know.

**Comment by gyurgyma** [comment]
Merged into dev and Master
