### ISSUE TITLE
Remove std::list from everywhere

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#141]
std::list is worse than std::vector in almost every case. 
We shouldn't have switched to use it.

Replace std::list with std::vector wherever it is used.

**Comment by lavinrp** [comment]
GameRegion::updatables and GameRegion::drawables were previously std::list they (and their getters/setters) are now std::vector.

All path finding related lists are staying for now. List was chosen for that because we pop the head off the list. We never fully iterate through the data structure.

Perhaps a queue instead of a vector?

**Comment by lavinrp** [comment]
queue wont allow for iterating which would be useful if we go to something like Theta* path finding. 
Changing to deque for now. deque allows for random access iteration.

With this data structure we may want to change pathfinding so that it doesn't require a flipping of the array at the end.

**Comment by gyurgyma** [comment]
Removed from passed review. This now fails review. Lets try to use vector everywhere possible. In the future, I think we ought to do actual performance testing before approving things like this. Maybe if you like, lets do it along with this change.
