### ISSUE TITLE
Fix FindGameBackbone

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#142]
FindGameBackbone seems to overwrite GB_LIBRARY_DYNAMIC_RELEASE twice instead of using GB_LIBRARY_DYNAMIC_DEBUG

**Comment by lavinrp** [comment]
Not marking as critical b/c the script seems to fall back and allow clients to build anyway.

**Comment by lavinrp** [comment]
Note:
This will need to be fixed independently in RE

**Comment by gyurgyma** [comment]
Merged into Dev
