### ISSUE TITLE
Improve Unsafe Interfaces

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#143]
AnimatedSprite::Animations is used in a few situations where it could be null.
Animations is currently a dumb pointer. the animations for each animated sprite are shared among many animated sprites. Animations should probably be a shared pointer.

There are probably other unsafe interfaces, acccessors, and mutators in the code.
We should fix these.

**Comment by lavinrp** [comment]
AnimatedSprite::update should be override not virtual

**Comment by lavinrp** [comment]
GameRegion has getters for children and neighbors that  return pointers to the mutable internal vectors.
Lets make these const reference returns to be safe.

Child and Neighbor have relations that can be broken and possibly produce a crash if someone removes a relation from the internal vector before the owning GameRegion's destruction. (It will always crash If they don't remove the other end of the relation).

**Comment by lavinrp** [comment]
Should GameRegion have ownership of its child regions?

**Comment by lavinrp** [comment]
@gyurgyma 
If we are going to do anything with naming the CB functions we should do it now.

**Comment by lavinrp** [comment]
Always throwing in RelativeRotationSprite setScale is really bad. We should stop this.

**Comment by lavinrp** [comment]
can we get rid of the std::string* in RandGen?
I see that we did that to get rid of the Msoft dllexport warning.

**Comment by lavinrp** [comment]
AnimationSet is a mess, but I dont think its unsafe

**Comment by gyurgyma** [comment]
@lavinrp 
> Always throwing in RelativeRotationSprite setScale is really bad. We should stop this.
   This was your idea. We didn't want it to be implemented. You are welcome to look into that issue.
> can we get rid of the std::string* in RandGen?
> I see that we did that to get rid of the Msoft dllexport warning.
   No, we need a seed that is convertible to string for any procedurally generated game. In this case, rather than having a seed converted somehow each time, it's way cleaner to just have a string that we convert to a seed within the class. That's kinda why we have a wrapper.

**Comment by gyurgyma** [comment]
Though, we do have a TODO in RandGen, we should do that now.

**Comment by gyurgyma** [comment]
>/// <summary> A vector of Animations </summary>
	using AnimationVector = std::vector<Animation>;
    /// <summary> A Pointer to a vector of Animations </summary>
    using AnimationVectorPtr = std::shared_ptr<AnimationVector>;

**Comment by gyurgyma** [comment]
AnimatedSprite looks like it takes in AnimationSet*s but basically immediately strips them to "AnimationVectorPtr". This is the same type of interface issue we didn't like with clusters. Maybe fixing this will help fix some of the naming issues and knowing who needs to interface with what types.

Also, I think that AnimatedSpriteInit needs renamed. I see no reason to have it redundant, especially if it is protected. Could it be done with constructor forwarding? If not, lets just fix the name.

**Comment by lavinrp** [comment]
I agree with everything said.
The RandGen comment was more about the * than the string

**Comment by lavinrp** [comment]
Lets try to fix AnimatedSprite and AnimationSet

We want AnimatedSprite to optionally resize to match the size of its current frame.
Make AnimationSet an interface or abstract class.
Animations should just be a vector of IntRect.
AnimationSet children should allow adding animations that have frames of arbitrary size, or animations that have uniform size.

**Comment by lavinrp** [comment]
Should animation set store its animations as pointers?

**Comment by lavinrp** [comment]
AnimationSet will only allow creation of animations with arbitrary sized frames. UniformAnimation set will inherit from AnimationSet and allow the user to specify one frame size. When adding an animation the user will then specify the row and col of that frame. The row and col will be combined with the animation size internally to produce the texture rect for the frame.

**Comment by lavinrp** [comment]
@gyurgyma 
We should provide a documentation comment for our Vec2Compare.
The name is ok. It could be Vector2Compare, but Vec2Compare describes it purpose well.

There was a build error with PlatformDemo. Just still including Point2D.h. Fixed.

Other than that it looks really good.

**Comment by lavinrp** [comment]
make vect2 compare constexpr

**Comment by gyurgyma** [comment]
IsVector2Less's operator() is now constexpr ... const. We need both for compilation, do we need both functionally? Maybe I'm not understanding constexpr completely.

**Comment by gyurgyma** [comment]
@lavinrp I think that the documention for AnimationSet::<iterators> needs to be clearer. "Const Iterator" is confusing cause it makes me thing "const iterator" over "const_iterator". Also, the same hold true for "Reverse iterator to the beginning/end...", which is arguably even more confusing. I mean, I get it, I just don't like this. I think it's mostly copy paste issues anyway.

**Comment by gyurgyma** [comment]
This is finished and merged into Dev
