### ISSUE TITLE
Clean up AnimationSet

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#144]
I dont think we should expose AnimationSet::framesToRects to clients.

I think adding getters and setters  for width and height and rows and cols and having those invoke framesToRects behind the scenes is a better interface. It also won't be too much of a performance hit b/c users shouldn't be changing the heights and rows/cols of a animation set often.

Perhaps a constructor and setter that take a texture outright too instead of making the user get the width and height from the texture.

**Comment by gyurgyma** [comment]
This is merged into dev
