### ISSUE TITLE
Make Array2D and Array3D const correct

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#148]
This is low priority, but may provide small performance gains and const is always god.

**Comment by lavinrp** [comment]
There wasn't much I could do here.
Array2D serves its purpose, but It may be time for us to replace it with boost's ND array.

The original purpose of implementing Array2D on our own was to keep the logic equivalent on the CPU and GPU (for use in pathfinding) but I don't think that's a priority anymore.

**Comment by gyurgyma** [comment]
Merged into Dev
