### ISSUE TITLE
Restructure GB ... Again

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#153]
GB Backbone should be renamed core.
core and Utils are probably all that's needed in base game backbone.

Navigation and Clusters should probably be broken out into children of GB specialized for specific game archetypes. 

Strategy, platform, etc..

Navigation
clusters
point
cec region
controls

**Comment by lavinrp** [comment]
I think the most important thing is to rename Backbone into Core and make clients import backbone/core, backbone/util, backbone/navigation instead of backbone, util, navigation.

**Comment by gyurgyma** [comment]
@lavinrp Does this mean separate dlls for each of the folders? or is it just about includes?

**Comment by lavinrp** [comment]
@gyurgyma 
Originally  when creating this issue I was concerned with dlls.
I think its more realistic that we do this with just includes for now.

**Comment by gyurgyma** [comment]
GB has been restructured to Core, Navigation, and Utils. Header and Source are the new folder names. There is an intermediate GameBackbone folder.
