### ISSUE TITLE
Possible Memory Leaks

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#155]
Valgrind is showing that we're leaking some stuff in the demo (and maybe in the tests). Linux people. Please take a look.

**Comment by lavinrp** [comment]
Valgrind's issues were solved with rather conservative use of smart pointers. I think we should switch to be using almost exclusively smart pointers, but that can be part of an enhancement.

I also commented out the pathfinder performance test as it made valgrind unusable.

**Comment by gyurgyma** [comment]
This is merged into dev
