### ISSUE TITLE
CompoundSprites should own Pointers

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#156]
currently compound sprites get a non-owning reference to their pointers.
Compound sprites should own their pointers.

Give compound sprites ownership of their pointers. Probably use std::unique_ptr.

**Comment by lavinrp** [comment]
@gyurgyma  since I'm here, Its worth pointing out that RelativeRotationSprite has a bunch of throwing constructors.

They throw when the components and the relative offsets dont match.
Would it make sense for the constructors to take a vector<pair<Sprite, Vector2f>>
That way it would be impossible to have a mismatch between offsets and sprites.

Additionally, are we sure we even want the offset constructors? I feel like for the work it takes a client to provide the offset vector they could have just moved the input sprite.

**Comment by gyurgyma** [comment]
I agree, we should look into that. Though I don't know that we care right now. I don't mind your first suggestion, though I'm not sure about the second. I think looking at the client use case for each would be an interesting thought experiment

**Comment by gyurgyma** [comment]
@lavinrp No sunk cost here. I genuinely thin this is our best option that we have for now. You did a good job implementing it as we discussed. I think it passes review solidly. When you get a chance, go ahead and merge it in.

**Comment by lavinrp** [comment]
This resulted in a major refactoring of ComoundSprite and RelativeRotationSprite
CompoundSprite now stores all of its components as value types (not as pointers).

CompoundSprite is not yet a recursive data structure. This is being left for a future enhancement. #182
