### ISSUE TITLE
Create script to run all vcpkg setup

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#161]
create python script that runs the setup.

conditionally run bootstrap
Install all libs that we want.
Move the lib dlls into the build folder.

**Comment by gyurgyma** [comment]
Completed for Windows. Take a look and then use it to fill out the linux and/or mac portions.

**Comment by lavinrp** [comment]
@flounderK 

This needs to be cleaned up.

Commented.

We need a -h and --help command. to print the options.

It would be great if we could also automate a little more. That isn't the most important thing though, and we shouldn't spend too much time here.
  * automatically download and bootstrap vcpkg
     * don't do the integrate step
  * automatically create the json files for visual studio and vscode??

**Comment by lavinrp** [comment]
Installs x86 on windows. We want our devs to be using x64. Should just be a quick fix.

**Comment by gyurgyma** [comment]
Add vcpkg rerunning bootstap, and upgrade anyway. It should be safe to do so.
.\vcpkg upgrade --no-dry-run

**Comment by lavinrp** [comment]
I dont think we should allow users to install without providing a path. If they don't provide a path we should just error out and print the help text.

**Comment by gyurgyma** [comment]
This is finished and merged into dev
