### ISSUE TITLE
Make GB usable

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#163]
Update ReadMe #166
UML #137 
User Guide #168
Comment up examples #169

**Comment by lavinrp** [comment]
For future reference the following links are helpful for correctly installing via cmake

https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/How-to-create-a-ProjectConfig.cmake-file
https://cmake.org/cmake/help/v3.8/module/CMakePackageConfigHelpers.html

**Comment by lavinrp** [comment]
@gyurgyma 
We can close this on close of #169
