### ISSUE TITLE
Make GB consumable by cmake

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#164]
We want GB on vcpkg. To do this, we need to make an install thing for cmake in order to do this.

**Comment by lavinrp** [comment]
Installed GB version is wrong. I used CMAKE_VERSION.

**Comment by lavinrp** [comment]
Remove cmake_minimum_required from export and install

**Comment by lavinrp** [comment]
check where config.cmake files go when using vcpkg

**Comment by lavinrp** [comment]
For future reference the following links are helpful for correctly installing via cmake

https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/How-to-create-a-ProjectConfig.cmake-file
https://cmake.org/cmake/help/v3.8/module/CMakePackageConfigHelpers.html

**Comment by lavinrp** [comment]
@gyurgyma 
*  Fixed the issues we talked about.
*  Added some logging. The logging also give hints to set non default options.
*  Broke some more stuff (new CMake options are required for devs, but having it off by default makes for sense if we want things like vcpkg to consume it. SFML doesn't make us built their test suite every time).
*  Added a small test project for testing the consumption of an Installed GB. This won't (and cant) be run by default. If we set up a CI server we can run it there.
    * We cant run the test by default because we cant force users to install GB on every build. We cant do that because we don't know before hand what build options they need.

**Comment by gyurgyma** [comment]
"gamebackbone_message("Using custom find module for Box2D. To use vcpkg provided Box2D set USE_VCPKG_BOX2D to ON")"
This reads really poorly, I think we should rework the last sentence

**Comment by gyurgyma** [comment]
Why do we need to set variables to run the demo? Is this a part of modularizing for clients?

**Comment by lavinrp** [comment]
comments resolved
