### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#166]
Update the readme to reflect the new way to install GB for both devs and end users.

**Comment by lavinrp** [comment]
@gyurgyma 
What is the file name for the user guide?

**Comment by lavinrp** [comment]
@gyurgyma 

Many of the links will be broken until this is merged into master. I have to hard code them and I'd rather not have to immediately patch master as soon as this goes in.

I created the links as if they were on the current branch, then changed the path to point to master (even for the files that dont exist on master yet).

**Comment by gyurgyma** [comment]
Merged into Dev
