### ISSUE TITLE
Make CompoundSprite sf::Drawable

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#172]
https://stackoverflow.com/questions/34458791/making-custom-types-drawable-with-sfml

Making something drawable is easy to implement and provides a more consistent API.
This also means that we can remove the extra CompoundSprite overloads from GameRegion.

**Comment by gyurgyma** [comment]
I updated CompoundSprite to inherit from sf::Drawable and implemented draw. I also removed  GameRegion::setDrawable(bool status, CompoundSprite* object).
I wish I could remove the specialization for setDrawAndUpdateable, though we need to specify that the object is both an updateable and a drawable. I feel like @lavinrp has told me we can do this in c++20? perhaps. Lets talk about that before merging this.

**Comment by gyurgyma** [comment]
We may also want to test this somehow.

**Comment by lavinrp** [comment]
@gyurgyma 
merged in, but does this require any documentation changes?

**Comment by gyurgyma** [comment]
Merged into Dev
