### ISSUE TITLE
Make GameRegion Drawable and Updatable

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#174]
behave -> update
add draw

GameRegion should be an updatable and a drawable. This will make a much cleaner API and allow for easier composition of multiple instances of GameRegion

**Comment by gyurgyma** [comment]
GameRegion now inherits from sf::Drawable and GB::Updatable. I implemented draw and changed behave to update. The meat of the change is in CoreEventController::coreDraw where now we just call draw on the activeRegion rather than its drawables.

**Comment by lavinrp** [comment]
@gyurgyma A bunch of virtual functions now need override

**Comment by gyurgyma** [comment]
Update ReadMe

**Comment by gyurgyma** [comment]
Merged into Dev
