### ISSUE TITLE
GameRegion needs copy/move contructors

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#176]
GameRegion isn't handling copy/move at all. This is a rule of 5 violation. 
Lets implement this functionality.
Other older classes of ours may also have this issue. Look into those.

**Comment by gyurgyma** [comment]
I discovered the missing constructors at the bottom in private:
	private:
		//deleted copy and assignment ctr
		GameRegion(const GameRegion&) = delete;
		GameRegion& operator=(const GameRegion&) = delete;
		GameRegion(GameRegion&&) = delete;
		GameRegion& operator=(GameRegion&&) = delete;

Wouldn't it be nice if there was some way to look at this class and see if it is NonCopyable and NonMoveable?

@lavinrp can you check if this is ok, and if so, maybe we need to move these to public to see them better.

**Comment by lavinrp** [comment]
@gyurgyma Yea, lets just put them in public.

I think we should stay away from the NonCopyable / NonMovable helper classes for now.
Looks like more of a c++ 03 thing.

**Comment by gyurgyma** [comment]
The following will want to default move constructors:
Compound Sprite
Relative Rotation
Updatable (delete copy) and children
NavigationGridData

**Comment by gyurgyma** [comment]
Done and Merged
