### ISSUE TITLE
Overload GameRegion::setDrawAndUpdateable to take a GameRegion

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#183]
GameRegion can currently store other GameRegions as drawables or updatables, which is great. There is however no way to set both with one call. I think that would be a really fast, and convenient upgrade.

Assuming GameRegions stay with dumb pointers, its signature would be:
void setDrawAndUpdateable(bool status, GameRegion* object);

**Comment by lavinrp** [comment]
Not required with #143
