### ISSUE TITLE
Correct RelativeRotationSprite Interface

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#185]
We have not implemented exceptions.
Fix these.

Fix lambda names.

**Comment by gyurgyma** [comment]
CompoundSprite also needs some lambda name correct. Specifically scaleFunction, but possibly more.

**Comment by lavinrp** [comment]
Needs testing

**Comment by lavinrp** [comment]
Needs initializer list

**Comment by gyurgyma** [comment]
This has been finished and I merged it into Dev, but the variable is being set in the constructors not in the initializer list. lets fix that.

**Comment by lavinrp** [comment]
@gyurgyma review

**Comment by gyurgyma** [comment]
"RelativeRotationSprite::RelativeRotationSprite (std::vector<sf::Sprite> components, std::vector<AnimatedSprite> animatedComponents,    sf::Vector2f position) :"

Tabs vs Spaces here (61).

Fix that one line an you have my blessing.

**Comment by lavinrp** [comment]
This has been closed a long time ago.
Just fixing that oversight
