### ISSUE TITLE
Fix TODO in RandGen and Remove in stdafx

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#190]
We have a TODO in RandGen that we actually need to do something about.

We also have two TODOs in UnitTests stdafx. These probably don't need to be TODOs and in fact should be removed.

**Comment by gyurgyma** [comment]
Test the std::runtime_error in RandGen::uniDist

**Comment by lavinrp** [comment]
@gyurgyma I created a branch with the test.
It actually brought up an issue.

I had already merged in the original branch because I'm dumb.

This should be a quick review.
i190-TestException

**Comment by gyurgyma** [comment]
Closed and Merged into Dev
