### ISSUE TITLE
Support Priority Drawing

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#194]
When setting a sprite as drawable the user should be able to define its priority. Higher priority gets drawn later and is thus on top.

This concept should also be applied to CompoundSprite.

GameRegion would maintain a sorted data structure (vector? Set?) of drawables.
Probably use a vector of tuple of priority and vector of drawable.
vector<tuple<int, vector<drawable*>>>

Each CompoundSprite is added at a single priority, but inside its own draw function it sorts its components based on their priorities.

**Comment by lavinrp** [comment]
Probably use the priority as an unsigned int.
If afraid of needing to reorder things later use an enum and cast

**Comment by lavinrp** [comment]
Unit test by mocking the renderer.

**Comment by gyurgyma** [comment]
This has been pulled back into progress because we need CompoundSprite to also have priority drawing. The GameRegion implementation seems good and should be copied into CompoundSprite.

**Comment by lavinrp** [comment]
Priority will be abstracted into a PriorityVector container.
CompoundSprite's API will mostly just forward to the PriorityVector container, though the SFINAE and priority api still need to be worked out.

**Comment by lavinrp** [comment]
Major considerations:
1. Priority Drawing and Non Priority Drawing as an option
    1. Ability to swap out underlying container
1. SFINAE should only allow the user to add drawables and transformables
    1. SFINAE needs to continue to work independent of the underlying container.
1. Type erasure should be retained and not copy pasted.
   1. only implemented once.

**Comment by lavinrp** [comment]
Possible implementations:
Template CompoundSprite on the underlying container.

Now that there are different containers the SFINAE needs to work regardless of where the underlying container stores its container.

Consider using CRTP.
Have the Base classes AddComponent be variadic and have it forward to the crtp child classes correct AddComponent overload.

```
#include <utility>

template <class crtpChild>
struct Foo
{
    template <typename... Ts>
    auto foo(Ts&&... args)
    {
        static_cast<crtpChild*>(this)->crtpChild::foo(std::forward(args)...);
    }

    int foo(int)
    {
        return 2;
    }
};

struct FooChild : Foo<FooChild>
{
    using super = Foo<FooChild>;
    using super::foo;

    int foo(int, int)
    {
        return 1;
    }
};


int main()
{
    FooChild child;
    return child.foo(1, 2);
}
```

The above CRTP pattern is really only useful if we want to provide a good default.
If users want to add their own implementations of AddComponent then the CRTP doesn't save them any work.

**Comment by lavinrp** [comment]
@gyurgyma 
Three test failures

error: in "CompoundSpriteTests/CompoundSprite_CTR/CompundSprite_MoveCtr_DoesMoveConstruction": check compoundSprite.isEmpty() == false has failed
../../../GameBackboneUnitTest/Source/CompoundSpriteTests.cpp(235): error: in "CompoundSpriteTests/CompoundSprite_CTR/CompundSprite_MoveCtr_DoesMoveConstruction": check compoundSprite2.getComponentCount(0) == 1 has failed
../../../GameBackboneUnitTest/Source/CompoundSpriteTests.cpp(254): error: in "CompoundSpriteTests/CompoundSprite_CTR/CompundSprite_MoveAssign_DoesCMoveAssign": check compoundSprite.isEmpty() == false has failed

*** 3 failures are detected in the test module "GameBackboneBoostUnitTest1"

**Comment by lavinrp** [comment]
The failures were simple. Fixed.
