### ISSUE TITLE
Platform demo cant support mouse and keyboard input at the same time

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#195]
When moving the player the mouse is somehow locked in place and unable to move.

**Comment by gyurgyma** [comment]
@lavinrp This issue doesn't happen on my desktop, so I tried plugging a mouse into my laptop and reproduce it and lo and behold, it fixed the issue. So this is only an issue with trackpads as far as I can tell. Likely its a driver or hardware bug. I'm not sure we have a solution here. What're your thoughts?

**Comment by lavinrp** [comment]
My thoughts are close
