### ISSUE TITLE
Animated Sprite setCurrentFrame doesnt imediately set the frame

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#197]
setCurrentFrame should visibly change the frame that is being displayed instead of waiting for the animation to run.

**Comment by lavinrp** [comment]
Requires 199 because of Demo changes

**Comment by gyurgyma** [comment]
@lavinrp what was alex's original use case here? Currently, you have it so setCurrentFrame requires runAnimation to have been called. This seems ok, and obviously would work if it was paused. But I feel like I feel like I remember alex using this to set the animation, potentially of the button. What was the reason runAnimation wasn't just called here? I am fine with this fix, I just want to check all the use cases we are trying to cover are in fact covered.

**Comment by lavinrp** [comment]
Add a better integration to the demo

**Comment by lavinrp** [comment]
@gyurgyma This demo is holding up this bug fix. Lets try to put this to bed by 9/14

**Comment by gyurgyma** [comment]
merged into dev
