### ISSUE TITLE
Add flags to cmake for compiler warnings

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#198]
adding flags like -Wzero-as-null-pointer-constant to our cmake

**Comment by lavinrp** [comment]
Make sure flags for both linux and windows are set

**Comment by gyurgyma** [comment]
https://stackoverflow.com/questions/43780157/cmake-externalproject-add-ignore-dependencys-cmake-warnings
https://stackoverflow.com/questions/15133332/ignore-only-show-errors-warnings-from-certain-directory-using-cmake

**Comment by gyurgyma** [comment]
Defined function for CMake: https://stackoverflow.com/questions/52135983/cmake-target-link-libraries-include-as-system-to-suppress-compiler-warnings

**Comment by gyurgyma** [comment]
W3/W4 replacal: https://stackoverflow.com/questions/2368811/how-to-set-warning-level-in-cmake
