### ISSUE TITLE
Fix failing Pathfinding Test

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#204]
PathFinderTests has a failing test.
Fix it.

**Comment by lavinrp** [comment]
The test was always broken.
A fix during earlier refactoring fixed a bug in the BOOST_CHECK of the test that was allowing it to pass before.

It was a test bug, not a PathFinder bug

**Comment by gyurgyma** [comment]
What was the reason for the fair then? It looks like you changed the path, but what was it that surfaced the fail?

**Comment by lavinrp** [comment]
The BOOST_CHECK was path.size() >= 0 before. That allowed it to pass with an empty path.
After you fixed it to be > 0 the test started (correctly) failing.

The maze was not solvable. I just made it solvable by removing a blocker that wasn't supposed to be there (and wasn't there in the comment that describes the intended shape of the maze)

**Comment by gyurgyma** [comment]
Ok, perfect, that makes a lot more sense now. Do we want there to be a comment about these types of things in tests, especially pathfinding tests which for me are really hard to logic through?

**Comment by gyurgyma** [comment]
Merged into Dev
