### ISSUE TITLE
Make CompoundSprite sf::Transformable

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#205]
CompoundSprite reimplements many of the pieces of API of sf::Transformable (move, rotate, scale, positions, etc). Some of the API in fact is not reimplemented (getRotation, getScale, Getting the entire Transform together, etc). We should likely utilize sf::Transformable for this problem, it would allow us to handle this all in one place.

We would need to explicitly call sf::Transformable::<function_name> within the nonvirtual CompoundSprite functions.

**Comment by gyurgyma** [comment]
Use Cases:
- Add all components and do nothing
- Add all components, set origin
- Set origin, add components
- Set origin, add components, set origin
- Add components, set origin, add components

**Comment by lavinrp** [comment]
we need to make sure to resolve any TODOs

**Comment by gyurgyma** [comment]
- SwirlySpriteDemo's InitCB functions should be called something else.
- Remove Position check from default constructor in tests

**Comment by lavinrp** [comment]
CompoundSprite now publicly inherits from sf::Transformable and behaves as RelativeRotationSprite did. RelativeRotationSprite has been removed.

Minor comment, demo, and test changes.
