### ISSUE TITLE
Consider removing TGUI

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#212]
Game region doesn't do anything with TGUI by default.
The gui is really only used in the demo.

Perhaps we should let users decide what GUI they want to depend on.
All they would have to do to use TGUI would be to add a TGUI::Gui member to their GameRegion child and add an TGUI::Gui::draw invocation to their draw call.

This would also allow clients to use other tools like Qt or SFGUI.

Downside is that it does make it slightly more difficult for clients to get any kind of GUI functionality.

**Comment by gyurgyma** [comment]
it needs to be on the game region because CEC calls into it to handle events

**Comment by gyurgyma** [comment]
So, after looking, there is a fairly easy way of removing the above problem. 
Firstly, in CEC::handleGuiEvent we call getGUI from the GameRegion, which it needn't do if we make a virtual handleGuiEvent on GameRegion.
A, perhaps, better idea, is to have CEC::handleEvent completely forward to the active region, thus completely moving the events to GameRegion (and if virtually, to any of its children).

**Comment by gyurgyma** [comment]
Also, it looks like there is an issue, in CEC::coreDraw where we draw the GUI. This is way bigger a deal, though can be solved by correctly engineering a solution in GameRegion::draw, or overriding coreDraw and static casting to a GameREgion and drawing the GUI.

**Comment by gyurgyma** [comment]
This isn't quite finished. We have three things left:
1. We need to edit the test to make sure they compile.
2. We need to change CMake for the dll to not include TGUI and in the exe to include TGUI. 
3. We need to update documentation for what dependencies are needed and where.
