### ISSUE TITLE
Unit Tests for AnimatedSprite

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#22]
Unit Test everything testable in this class.
Cover all edge cases.

**Comment by lavinrp** [comment]
Worked on as part of [`i13`](https://github.com/lavinrp/GameBackbone/issues/13)

**Comment by lavinrp** [comment]
1. 

Not a lot of commenting in the test file. We may want more for our test files. Thoughts?

2.

Thoughts on the test suites?

**Comment by gyurgyma** [comment]
1. Oh god. I think that either each test needs a comment or two, or potentially, a short comment for each BOOST_CHECK. I'm more leaning for the second of the two, but to be fair, both could be helpful.

2. I think they're fine. If you like, you could add a a couple subsuites still. Maybe one for testing different constructors or initialization, one for testing the steps, one for setting values.

**Comment by bauerbp** [comment]
I agree with michael

**Comment by lavinrp** [comment]
How about now?

**Comment by lavinrp** [comment]
finished as part of #13
