### ISSUE TITLE
Unit Test Pathfinder

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#31]
Unit Test everything testable in this class.
Cover all edge cases.

This One is critical.

The performance and correctness of PathFinder will have significant impact on everything from this point forward.

**Comment by lavinrp** [comment]
initial testing work under way [in dedicated branch](https://github.com/lavinrp/GameBackbone/tree/Pathfinder_tests)

**Comment by lavinrp** [comment]
All tests will need to be refactored after switch to square grid.

**Comment by lavinrp** [comment]
Need unit test for differing weights.

**Comment by lavinrp** [comment]
Be sure to test a scenario where weights result in the cost of reaching a square to change.

**Comment by gyurgyma** [comment]
I added a new test, that uses different weights. In theory, this is done.

**Comment by lavinrp** [comment]
@gyurgyma your changes are good and run good.
closing.
