### ISSUE TITLE
Resize view with window

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#38]
When the window resizes the view should expand to the new size.
This will prevent stretching of items in the window.

http://www.sfml-dev.org/tutorials/2.4/graphics-view.php

**Comment by lavinrp** [comment]
This should be done in GameBackboneExe main.cpp and will just be used as an example of how to do things for games that build off of backbone.

**Comment by bauerbp** [comment]
Add case for Event::Resize.
