### ISSUE TITLE
add Array2D.at(x, y)

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#49]
Add "at" function to array2D.

It should behave exactly like operator().

see implementation of std::vector.at() for use details

This should allow for cleaner accessing of array elements when the Array2D is a pointer.

copy unit tests for array2D operator()

to ensure that functionality is correct.

**Comment by gyurgyma** [comment]
We already had a getter and setter for this guy. I've removed those and added "at" as an accessor using the overloaded operator.
