### ISSUE TITLE
Look into possible GUI Libs

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#51]
SFGUI and TGUI both look promising.

TGUI seems like the easiest and best fit at the moment

[TGUI](https://tgui.eu/)
[SFGUI](http://sfgui.sfml-dev.de/)

**Comment by gyurgyma** [comment]
https://tgui.eu/download/
https://tgui.eu/tutorials/v0.7/visual-studio-precompiled/

This is the TGUI stuff. Let's look into using that.

**Comment by lavinrp** [comment]
Ready to call this done. TGUI seems like the way to go. I've integrated TGUI into GameRegion and added an example of how to use it into NavigationDemoRegion.

Reviewers: Take a look at the use of SELECTED_NAVIGATOR_BUTTON_TYPE and the three new handle functions in NavigationDemoRegion to see if this is how you think things should be structured.
Also look into the constructors for NavigationDemoRegion (specifically the end of the "init" function).

Finally take a look at "initGUI".
