### ISSUE TITLE
create a batch script to run the boost unit tests

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#60]
Batch script should:
   -Run the Test Group
   -If testgroup Failed
      -rerun each test in the group
        -Push which tests failed to log file
  -If testgroup pass
     -Push to log file

**Comment by lavinrp** [comment]
This is only necessary so long as we are using boost test without the visual studio adapter.

**Comment by lavinrp** [comment]
Do we still need to do this?
