### ISSUE TITLE
Look into simplifying constructors

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#63]
Two things can be done:
-Inheriting Constructors (using A:A())
-Default Constructors using (= default)

These could make the code simpler, easier to read, and allow for inherited changes.

**Comment by lavinrp** [comment]
After some experimentation I have come to the conclusion that constructor inheritance will be less useful than recently thought. It calls an empty constructor for the child class, not the user defined default constructor. this produces unacceptable results in all current situations where constructor inheritance would be used.

explicit declaration of default and deleted constructors and operator= have been added to all GB classes.

All GB classes should now adhere to the rule of 5.
