### ISSUE TITLE
AnimatedSprite.animations of size 0 and then trying to run/update.

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#73]
-I think that if we try to run/update an AnimatedSprite that has an animations that is empty(not null, though maybe that will break too) it will break. I think honestly this should be something to do with Exception handling. Ryan please take a look.

1. Look into the issue.
2. Add a check in update and possibly other places.
3. Add AutoTests for this case for all of the run modes, and maybe a few more.

**Comment by lavinrp** [comment]
Now throws exception when an empty animation is run.

**Comment by lavinrp** [comment]
Empty and 1 frame animations are now supported. Attempting to run an empty animation will throw an exception.

1 frame animations will never try to change frame.
