### ISSUE TITLE
Fix ReusableObjects in CompoundSpriteTests

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#76]
Somehow this isn't causing a detected memory leak, but sprite is never deleted in ReusableObjects.

I have tried to use the members of ReusableObjects in fixture test cases and I always got corrupted memory. This is likely related to the no memory leaks thing.

Figure out whats wrong. It could be producing false results in our tests.

**Comment by Christopher-Ochs** [comment]
ReusableObjects in both AnimateSptriteTests.cpp and CompoundSpriteTest.cpp were both in the anonymous scope causing issues with the auto test.  To fix this the reusable object is moved into the first boost_auto_test_suite.
