### ISSUE TITLE
Add A function to UtilMath to randomly create clusters

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#78]
Use network science to randomly create clusters of adjacent nodes given an Array2D. Store the clusters in a class Cluster

cluster should store the number of nodes within it along with the 2d coordinates (intPair) of the nodes.

**Comment by bauerbp** [comment]
✨✨✨✨✨✨✨
✨! _NETWORK SCIENCE_  ! ✨ 
✨✨✨✨✨✨✨✨

**Comment by lavinrp** [comment]
✨✨✨✨✨✨✨✨
✨!! NETWORK SCIENCE!!  ✨
✨✨✨✨✨✨✨✨

**Comment by bauerbp** [comment]
i78-MapGenerator is the initial version of the map generator.  I will create somewhere between 1-5 clusters of various sizes by default.  Custom clusters can be made by user with just a couple lines of code.  Things which still need to happen are:
Using our homemade random number generator for creating clusters,
Add ability to create features in graph before clusters are generated (for example, a river),
make sure that there is a path from one point of the graph to another,
a few other things.

**Comment by malexmc** [comment]
From our in-person meeting today, everyone is happy with the work so far and the direction this is going in 👍. Here are the discussed areas of interest and concern:

Interest:
    - Check double adding
    - How many clusters?
    - Rough size of each cluster?
    - Determine shape of cluster
Concern:
    - Remove struct
    - RandGen
    - Point2D<Dimensions>
    - Add check to GenerateRandomOptionsVector to be sure that the vector is empty. Throw exception if not empty

**Comment by lavinrp** [comment]
cluster constructor has unused std::multimap<Point2D<int>

**Comment by lavinrp** [comment]
Purpose of function getClusterGenerationOptions and member clusterOption are ambiguous.
Rename function / member to be more descriptive + doxygen comments on function should celar that up. 

It seems to me that pointToClusterMap and the logic for checking if a point belongs in another cluster belongs in clusterGreenhouse, not Cluster.

Why should a cluster care if its point is in another cluster? Why should it know what points are in another cluster?
These responsibilities are specific to our one current intended use for cluster. The class would be more versatile without these.
Move them to ClusterGreenhouse. ClusterGreenhouse is responsible for growing the clusters to fit our specifications. 

A cluster shouldn’t care if the point being added to it is random. Rename the member of addPointToCluster to newPoint or something that isn’t specific to our current use case.
Change comment for addPointToCluster to avoid specifics of current use case. 

We need to finish adding comments to some remaining functions and clean up the duplicated comment for moveIterator.

moveIterator looks like it will break if it is asked to move past the number of points in borderPointSet. This should be protected against, or we should add a custom exception to indicate that that is what happened if it should never happen.

**Comment by lavinrp** [comment]
I still dont think cluster should know about its frequency. Can you explain why you want this here instead of an input to ClusterGreenhouse?

**Comment by lavinrp** [comment]
since generateClusteredGraph always takes in frequencies, can we remove the frequencies input from the greenhouse constructor?

**Comment by bauerbp** [comment]
I think that I'll rather keep the frequencies as an input to the constructor and remove it from generateClusteredGraph.  This way, the greenhouse will be populated once it's created.

**Comment by bauerbp** [comment]
closing issue
