### ISSUE TITLE
Discuss Moving Build Paths To Environment Vars

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#80]
Right now build paths in GB are relative paths from the locations of the vs project. This is useful b/c it means that after downloading the project and the required libs that developers dont have to do any work to make things build.

We start running into issues when we use GB as a sub-module of another project (like RE). b/c GB is then one folder deeper in the structure the paths it searches for are invalid. The current solution for this is to simply copy SFML and boost a second time and place them where GB expects them.

This will become inefficient as GB grows in size and requires more and more 3rd party dlls. This also becomes cumbersome as the number of projects using GB grows.

One possible solution is to change the compiler options for GB to use environment variables to compile.
Each developer would have to set the environment variables to the absolute path of their own location for the 3rd party dlls and libs. The benefits of this solutions is that no developer would have to keep several copies of each 3rd party resource that GB uses.

**Comment by gyurgyma** [comment]
Well, the relative paths aren't really an issue for RE:
1. I hate that it's above the whole folder, so I moved it down.
   a. GB and RE are sharing the same SFML contained one level above the GB and the RESln.
   b. This is cleaner and keep all of our possible Dlls right close to where they will be used.

As for the multiple copies, I agree that could need worked on, but I still think I prefer relative paths. I don't particularly like the idea of separating my Dlls from my projects, even though I would be able to handle it. I have always thought that that sort of stuff belonged together.

**Comment by lavinrp** [comment]
Environment variables will be used.

**Comment by lavinrp** [comment]
see [this ](https://docs.google.com/document/d/1LuGAUMPJGSkP4ukLqv6krB8fhjWFa_hiWGKzwd4ImJw/edit?usp=sharing)page for information on how to set up environment vars
