### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#81]
std::rand is trash. We should look into using a different random number generation.

Generator must:
-Have uniform distribution (at least)
-Use seeds (would help if it's a string)
-Produce reproducible values(ie: pseudorandom not truly random)

Ryan and I have discussed at length what this could be. I am under the impression that we should add a class to wrap whatever this function happens to be in order to allow for easy changing or options, as well as inheriting so that the client/applications can change/add to our set of functionality.

This page looks to have some great information on it about what is good to use:
http://en.cppreference.com/w/cpp/numeric/random

I think <random> is the best library for us to look into. What do yall think?

**Comment by lavinrp** [comment]
Should have at least 2 unit tests.
1) Two generators. Both have same seed. Ensure get same values.
2) Two generators. Get different seeds. Ensure non-identical output.

**Comment by lavinrp** [comment]
`double RandGen::UniDist(double min, double max)`
has no code difference from 
`double RandGen::UniDist()`

the passed in min and max seem to be unused.

**Comment by lavinrp** [comment]
see branch i81-proposed_changes

**Comment by lavinrp** [comment]
1) There are currently no tests for the two argument overload of uniDist. We should make at least one.
2) We may want to throw an error if min > max.

**Comment by lavinrp** [comment]
Now we just need to clean up the warnings

**Comment by lavinrp** [comment]
Warnings cleaned up
