### ISSUE TITLE
Unit Test GameRegion's GUI functionality

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#86]
When GUIs were added to GameRegion the addition was not properly tested.

Modify the default constructor test to ensure that the GUI is not null, but correctly constructed with a default tgui::gui constructor.

Create a unit test for the constructor that takes in a window. This constructor should test everything that the other constructor tests, but also test that the GUI is constructed and references the passed window.

Add a test for the getGui function. Ensure that it returns a mutable reference to the GUI.

**Comment by malexmc** [comment]
i86-GameRegionGUITests: 
    -Added GUI != null check to default GameRegion ctr
    -Added test for GameRegion ctr with window parameter 
    -Added test for getGUI. 

     NOTE: CoreEventController_RunLoop_No_Window_Event test now breaks. Deemed acceptable by @lavinrp
