### ISSUE TITLE
Have CoreEventController listen for Region Change events

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#87]
GameRegion should store a function pointer to be called whenever it decides to change active regions.
CoreEventController should pass one of its own member functions to each GameRegion.

The function would take in a GameRegion* and set the CoreEventController's activeGameRegion to the passed GameRegion*.

This means that CoreEventController wont have to check if it needs to change activeRegionis every frame.

**Comment by lavinrp** [comment]
@gyurgyma @bauerbp @malexmc  ready for review

**Comment by gyurgyma** [comment]
Looks good but you really ought to rename the method on GameRegion to setWhateverWhateverCB. The actual function on CoreEventController should also have newActiveRegion instead of newRegion.

**Comment by lavinrp** [comment]
Requested changes have been made.

**Comment by gyurgyma** [comment]
In CoreEventController.h, you spelled Active as Acive. Everything else looks good.

**Comment by lavinrp** [comment]
corrections made
