### ISSUE TITLE
GameRegion to return const vectors for drawables and updaeables.

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#88]
getDrawables and getUpdatables currently return mutable data. This encourages devs to do unsafe things with them.

See if changing these functions to return immutable data breaks everything.

**Comment by lavinrp** [comment]
@malexmc this looked ready when I used it today. Is there anything else you want do do on this? or am I good to merge into dev?

**Comment by malexmc** [comment]
@lavinrp This is good on the GameBackbone side, but I remember we discussed making those few small changes to RenegadeEmpire. Is that tracked with a separate issue?
