### ISSUE TITLE
GB::FileWriter

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#92]
Create a new class called FileWriter that will have the ability to save TSV/CSV/etc, and std::strings.
This should essentially be the opposite or GB::FileReader.

The TSV function should take (filePath, Array2D<string>, delimiter) and possibly a few other things.

The string function should take (filePath, std::string) and then just dump the string into the filepath. Possibly have a toggle for overwrite vs append.

Good place to start:
http://www.cplusplus.com/forum/beginner/36080/

**Comment by gyurgyma** [comment]
As a double extra quadruple check, the file that takes strings should save the strings as binary. they will have heavy potential to be something that will be treated improperly. Proceed with caution:
https://www.gamedev.net/forums/topic/572039-c-xor-encryption/

**Comment by malexmc** [comment]
i92-FileWriter:
    -Created the FileWriter class which can write formatted strings to binary files and can convert GB::Array2D objects to formatted strings.
    -Added an exception to BackboneBaseExceptions.h to be thrown when a bad Array2D it passed into FileWriter::createWritableString().

This class is functionally complete, but requires a way to test it. Perhaps running it, hashing the output file, and comparing all future runs to a hashed file that was manually verified could work.

**Comment by gyurgyma** [comment]
@malexmc I went to review this but I'm not seeing it. Are you sure you pushed it?
