### ISSUE TITLE
Upgrade GB::FileReader

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#93]
FileReader needs a new function to take a string and a filePath and save the string. This would method needs to not really care about newlines. 

Good starting point:
http://www.cplusplus.com/forum/beginner/36080/
https://stackoverflow.com/questions/32169936/optimal-way-of-reading-a-complete-file-to-a-string-using-fstream

**Comment by gyurgyma** [comment]
As a double extra quadruple check, the function should read the strings as binary. They will have heavy potential to be something that will be treated improperly. Proceed with caution:
https://www.gamedev.net/forums/topic/572039-c-xor-encryption/

**Comment by gyurgyma** [comment]
There is a serious issue here if a file ends in '\0' we're deleting it no matter what. This is very bad for encryption.

**Comment by lavinrp** [comment]
@gyurgyma @Christopher-Ochs @Spyder00777 
Do we want to have an overload of readFile, or some helper function that takes in a string and outputs the same Array2D of strings that readFile does?

It seems that we dont have a good way to go from a binary file to the Array2D<string> that things like RE expect.

**Comment by lavinrp** [comment]
@gyurgyma @Christopher-Ochs @Spyder00777 
Can we move the test files into the directory for the the tests?
Do they have to be in the GameBackbone base directory?

I don't really like having those just floating around in the root directory for GB

**Comment by gyurgyma** [comment]
@lavinrp ideally we put them in a testFile folder. That seems to make the most sense to me. I planned to do it eventually, I just wanted to make sure stuff worked first.

**Comment by gyurgyma** [comment]
Merged into i97
