### ISSUE TITLE
Add class to convert between NavigationGrd coordinates and SF::Window coordinates

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#95]
Create a class to facilitate conversion (both directions) between NavigationGrid coordinates and the coordinates of the SF::Window.

This class should store the offset of the grid from the windows origin, and the width of each GridSquare.

When converting from NavGrid coordinates to Window coordinates the output should be the window coordinates corresponding to the center of the center of the navigation grid.

When converting from window coordinates to NavGrid coordinates the output should be the index of the grid square that contains the passed window coordinates.

If a window coordinate is passed that does not have a corresponding NavGrid coordinate return (-1,-1).

**Comment by gyurgyma** [comment]
This functionality has been merged into Dev
