### ISSUE TITLE
Change NavigationDemoRegion's VisualizationGrid to inherit from NavigationGridData

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#98]
The intent of NavigationGridData is to be inherited be another structure and add your own members to it (ei: color). Let's update this class to actually use this style of visualization.

**Comment by lavinrp** [comment]
Think I fixed memory issue. initAllNavigationGridValues was the culprit.
This function is critical, but has no direct unit tests.

We should add some direct unit tests, including tests with inheritance to ensure that we never have a regression in this area.

**Comment by lavinrp** [comment]
I added a test to ensure that inheritance works here. I also tried using the new test back before the fix. The test broke without the fix, but works now.

I  think this one is safe.

**Comment by lavinrp** [comment]
@gyurgyma 

Is this issue good to close now?

**Comment by gyurgyma** [comment]
This will be good to Close as soon as issue 91 goes in.

**Comment by gyurgyma** [comment]
Merged into Dev
